In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

# **Part 1 - Data Preprocessing**

**1.1 Importing the Dataset**

In [2]:
#https://www.kaggle.com/uciml/default-of-credit-card-clients-dataset
#https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients
df = pd.read_csv('/UCI_Credit_Card.csv', index_col=0)
df  #default.payment.next.month is the label where 1 = defaulted, 0 = paid

LIMIT_BAL  SEX  ...  PAY_AMT6  default.payment.next.month
ID                     ...                                      
1        20000.0    2  ...       0.0                           1
2       120000.0    2  ...    2000.0                           1
3        90000.0    2  ...    5000.0                           0
4        50000.0    2  ...    1000.0                           0
5        50000.0    1  ...     679.0                           0
...          ...  ...  ...       ...                         ...
29996   220000.0    1  ...    1000.0                           0
29997   150000.0    1  ...       0.0                           0
29998    30000.0    1  ...    3100.0                           1
29999    80000.0    1  ...    1804.0                           1
30000    50000.0    1  ...    1000.0                           1

[30000 rows x 24 columns]

**1.2 Data Cleanup**

In [3]:
df['default.payment.next.month'].unique() #default.payment.next.month is the label where 1 = defaulted, 0 = paid

array([1, 0])

In [4]:
df.isnull().sum() #no null data which is nice

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

**1.3 Separating Inputs and Label**

In [5]:
X = df.iloc[:, :-1].values #take all rows and index columns from 0 to 23
y = df.iloc[:, -1].values #take all rows of column 24 which is the label

print(X)
print(y[0:10])

[[2.0000e+04 2.0000e+00 2.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.2000e+05 2.0000e+00 2.0000e+00 ... 1.0000e+03 0.0000e+00 2.0000e+03]
 [9.0000e+04 2.0000e+00 2.0000e+00 ... 1.0000e+03 1.0000e+03 5.0000e+03]
 ...
 [3.0000e+04 1.0000e+00 2.0000e+00 ... 4.2000e+03 2.0000e+03 3.1000e+03]
 [8.0000e+04 1.0000e+00 3.0000e+00 ... 1.9260e+03 5.2964e+04 1.8040e+03]
 [5.0000e+04 1.0000e+00 2.0000e+00 ... 1.0000e+03 1.0000e+03 1.0000e+03]]
[1 1 0 0 0 0 0 0 0 0]


**1.4 Train Test Split**

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.24)

X_train

array([[1.40000e+05, 2.00000e+00, 2.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.60000e+05, 1.00000e+00, 1.00000e+00, ..., 9.90000e+01,
        1.72104e+05, 3.00130e+04],
       [4.00000e+05, 2.00000e+00, 1.00000e+00, ..., 5.60000e+01,
        6.87000e+02, 8.00000e+02],
       ...,
       [3.20000e+05, 2.00000e+00, 1.00000e+00, ..., 8.50000e+03,
        1.30000e+04, 1.50000e+04],
       [1.30000e+05, 2.00000e+00, 3.00000e+00, ..., 9.26100e+04,
        3.27200e+03, 3.33200e+03],
       [5.20000e+05, 1.00000e+00, 1.00000e+00, ..., 5.70100e+03,
        6.00100e+03, 6.00100e+03]])

**1.5 Feature Scaling**

In [7]:
#so here we're just scaling all our values using the following formula: z = (x - u) / s
#x is the input, u is the mean, s is the standard deviation
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
#we do this because models normally perform better when numerical input variables are scaled to a standard range
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_test

array([[-1.05959192,  0.81448368,  1.44688809, ..., -0.22466563,
        -0.22988925, -0.22290955],
       [ 2.55871724, -1.22777168, -1.08236503, ...,  3.38402218,
         2.88759469,  5.26370007],
       [ 2.25077603, -1.22777168, -1.08236503, ...,  0.0809849 ,
         0.20273834,  0.04407136],
       ...,
       [-0.90562132, -1.22777168,  1.44688809, ..., -0.18786982,
        -0.05297129, -0.28917162],
       [ 0.0951876 , -1.22777168, -1.08236503, ..., -0.02228868,
         0.01021369, -0.06829806],
       [ 0.0182023 , -1.22777168,  0.18226153, ...,  0.0083745 ,
        -0.11615628, -0.17873484]])

# **Part 2 - Training and Evaluating Each Model**

**2.1 Logistic Regression**

In [8]:
lr = LogisticRegression(max_iter=200)
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
pred_lr = lr.predict(X_test)
pred_lr

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.81      0.97      0.89      5596
           1       0.72      0.22      0.34      1604

    accuracy                           0.81      7200
   macro avg       0.77      0.60      0.61      7200
weighted avg       0.79      0.81      0.77      7200



In [11]:
print(confusion_matrix(y_test,pred_lr)) 

[[5455  141]
 [1245  359]]


**2.2 Random Forest**

In [12]:
rf = RandomForestClassifier(n_estimators=1000)
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [13]:
pred_rf = rf.predict(X_test)

In [14]:
print(classification_report(y_test,pred_rf)) 

              precision    recall  f1-score   support

           0       0.84      0.94      0.89      5596
           1       0.65      0.36      0.47      1604

    accuracy                           0.82      7200
   macro avg       0.75      0.65      0.68      7200
weighted avg       0.80      0.82      0.79      7200



In [15]:
print(confusion_matrix(y_test,pred_rf)) 

[[5286  310]
 [1021  583]]


**2.3 Decision Tree**

In [16]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [17]:
pred_dt = dt.predict(X_test)

In [18]:
print(classification_report(y_test,pred_dt)) 

              precision    recall  f1-score   support

           0       0.83      0.81      0.82      5596
           1       0.38      0.41      0.39      1604

    accuracy                           0.72      7200
   macro avg       0.60      0.61      0.60      7200
weighted avg       0.73      0.72      0.72      7200



In [19]:
print(confusion_matrix(y_test,pred_dt)) 

[[4518 1078]
 [ 953  651]]
